name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:        ${{ secrets.AWS_REGION }}          # e.g. ap-northeast-2 :contentReference[oaicite:0]{index=0}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2                  # 로그인 액션 :contentReference[oaicite:1]{index=1}

      - name: Build & Push Docker image
        env:
          REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}            # e.g. 1234....amazonaws.com/my-app :contentReference[oaicite:2]{index=2}
          IMAGE_TAG:  ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Tag “latest” and push
        run: |
          docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker tag  $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:latest
